//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aeroflot
{
    using System;
    using System.Collections.Generic;
    
    public partial class pokupki
    {
        public int id { get; set; }
        public int id_klient { get; set; }
        public int id_reis { get; set; }
        public string status { get; set; }
        public virtual reis reis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual klients klients { get; set; }
        
        
    }
}
